<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterWiseOperationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('machine_wise_operations')->insert(
            [
                ['machine_id' => 1, 'operation_id' => '29'],
                ['machine_id' => 1, 'operation_id' => '30'],
                ['machine_id' => 1, 'operation_id' => '31'],

                ['machine_id' => 2, 'operation_id' => '29'],
                ['machine_id' => 2, 'operation_id' => '30'],
                ['machine_id' => 2, 'operation_id' => '31'],

                ['machine_id' => 3, 'operation_id' => '29'],
                ['machine_id' => 3, 'operation_id' => '30'],
                ['machine_id' => 3, 'operation_id' => '31'],

                ['machine_id' => 4, 'operation_id' => '29'],
                ['machine_id' => 4, 'operation_id' => '30'],
                ['machine_id' => 4, 'operation_id' => '31'],

                ['machine_id' => 5, 'operation_id' => '29'],
                ['machine_id' => 5, 'operation_id' => '30'],
                ['machine_id' => 5, 'operation_id' => '31'],

                ['machine_id' => 6, 'operation_id' => '29'],
                ['machine_id' => 6, 'operation_id' => '30'],
                ['machine_id' => 6, 'operation_id' => '31'],

                ['machine_id' => 7, 'operation_id' => '21'],
                ['machine_id' => 7, 'operation_id' => '22'],
                ['machine_id' => 7, 'operation_id' => '23'],
                ['machine_id' => 7, 'operation_id' => '24'],
                ['machine_id' => 7, 'operation_id' => '25'],
                ['machine_id' => 7, 'operation_id' => '26'],
                ['machine_id' => 7, 'operation_id' => '27'],
                ['machine_id' => 7, 'operation_id' => '28'],

                ['machine_id' => 8, 'operation_id' => '37'],
                ['machine_id' => 8, 'operation_id' => '38'],
                ['machine_id' => 8, 'operation_id' => '39'],
                ['machine_id' => 8, 'operation_id' => '40'],

                ['machine_id' => 9, 'operation_id' => '37'],
                ['machine_id' => 9, 'operation_id' => '38'],
                ['machine_id' => 9, 'operation_id' => '39'],
                ['machine_id' => 9, 'operation_id' => '40'],

                ['machine_id' => 10, 'operation_id' => '29'],
                ['machine_id' => 10, 'operation_id' => '30'],
                ['machine_id' => 10, 'operation_id' => '31'],
                ['machine_id' => 10, 'operation_id' => '32'],
                ['machine_id' => 10, 'operation_id' => '33'],
                ['machine_id' => 10, 'operation_id' => '34'],
                ['machine_id' => 10, 'operation_id' => '35'],
                ['machine_id' => 10, 'operation_id' => '36'],

                ['machine_id' => 11, 'operation_id' => '29'],
                ['machine_id' => 11, 'operation_id' => '30'],
                ['machine_id' => 11, 'operation_id' => '31'],
                ['machine_id' => 11, 'operation_id' => '32'],
                ['machine_id' => 11, 'operation_id' => '33'],
                ['machine_id' => 11, 'operation_id' => '34'],
                ['machine_id' => 11, 'operation_id' => '35'],
                ['machine_id' => 11, 'operation_id' => '36'],

                ['machine_id' => 12, 'operation_id' => '37'],
                ['machine_id' => 12, 'operation_id' => '38'],
                ['machine_id' => 12, 'operation_id' => '39'],
                ['machine_id' => 12, 'operation_id' => '40'],

                ['machine_id' => 13, 'operation_id' => '29'],
                ['machine_id' => 13, 'operation_id' => '30'],
                ['machine_id' => 13, 'operation_id' => '31'],
                ['machine_id' => 13, 'operation_id' => '32'],
                ['machine_id' => 13, 'operation_id' => '33'],
                ['machine_id' => 13, 'operation_id' => '34'],
                ['machine_id' => 13, 'operation_id' => '35'],
                ['machine_id' => 13, 'operation_id' => '36'],

                ['machine_id' => 14, 'operation_id' => '29'],
                ['machine_id' => 14, 'operation_id' => '30'],
                ['machine_id' => 14, 'operation_id' => '31'],
                ['machine_id' => 14, 'operation_id' => '32'],
                ['machine_id' => 14, 'operation_id' => '33'],
                ['machine_id' => 14, 'operation_id' => '34'],
                ['machine_id' => 14, 'operation_id' => '35'],
                ['machine_id' => 14, 'operation_id' => '36'],

                ['machine_id' => 15, 'operation_id' => '29'],
                ['machine_id' => 15, 'operation_id' => '30'],
                ['machine_id' => 15, 'operation_id' => '31'],
                ['machine_id' => 15, 'operation_id' => '32'],
                ['machine_id' => 15, 'operation_id' => '33'],
                ['machine_id' => 15, 'operation_id' => '34'],
                ['machine_id' => 15, 'operation_id' => '35'],
                ['machine_id' => 15, 'operation_id' => '36'],

                ['machine_id' => 16, 'operation_id' => '21'],
                ['machine_id' => 16, 'operation_id' => '22'],
                ['machine_id' => 16, 'operation_id' => '23'],
                ['machine_id' => 16, 'operation_id' => '24'],
                ['machine_id' => 16, 'operation_id' => '25'],
                ['machine_id' => 16, 'operation_id' => '26'],
                ['machine_id' => 16, 'operation_id' => '27'],
                ['machine_id' => 16, 'operation_id' => '28'],

                ['machine_id' => 17, 'operation_id' => '21'],
                ['machine_id' => 17, 'operation_id' => '22'],
                ['machine_id' => 17, 'operation_id' => '23'],
                ['machine_id' => 17, 'operation_id' => '24'],
                ['machine_id' => 17, 'operation_id' => '25'],
                ['machine_id' => 17, 'operation_id' => '26'],
                ['machine_id' => 17, 'operation_id' => '27'],
                ['machine_id' => 17, 'operation_id' => '28'],

                ['machine_id' => 18, 'operation_id' => '21'],
                ['machine_id' => 18, 'operation_id' => '22'],
                ['machine_id' => 18, 'operation_id' => '23'],
                ['machine_id' => 18, 'operation_id' => '24'],
                ['machine_id' => 18, 'operation_id' => '25'],
                ['machine_id' => 18, 'operation_id' => '26'],
                ['machine_id' => 18, 'operation_id' => '27'],
                ['machine_id' => 18, 'operation_id' => '28'],

                ['machine_id' => 19, 'operation_id' => '21'],
                ['machine_id' => 19, 'operation_id' => '22'],
                ['machine_id' => 19, 'operation_id' => '23'],
                ['machine_id' => 19, 'operation_id' => '24'],
                ['machine_id' => 19, 'operation_id' => '25'],
                ['machine_id' => 19, 'operation_id' => '26'],
                ['machine_id' => 19, 'operation_id' => '27'],
                ['machine_id' => 19, 'operation_id' => '28'],

                ['machine_id' => 20, 'operation_id' => '21'],
                ['machine_id' => 20, 'operation_id' => '22'],
                ['machine_id' => 20, 'operation_id' => '23'],
                ['machine_id' => 20, 'operation_id' => '24'],
                ['machine_id' => 20, 'operation_id' => '25'],
                ['machine_id' => 20, 'operation_id' => '26'],
                ['machine_id' => 20, 'operation_id' => '27'],
                ['machine_id' => 20, 'operation_id' => '28'],

                ['machine_id' => 21, 'operation_id' => '21'],
                ['machine_id' => 21, 'operation_id' => '22'],
                ['machine_id' => 21, 'operation_id' => '23'],
                ['machine_id' => 21, 'operation_id' => '24'],
                ['machine_id' => 21, 'operation_id' => '25'],
                ['machine_id' => 21, 'operation_id' => '26'],
                ['machine_id' => 21, 'operation_id' => '27'],
                ['machine_id' => 21, 'operation_id' => '28'],

                ['machine_id' => 22, 'operation_id' => '21'],
                ['machine_id' => 22, 'operation_id' => '22'],
                ['machine_id' => 22, 'operation_id' => '23'],
                ['machine_id' => 22, 'operation_id' => '24'],
                ['machine_id' => 22, 'operation_id' => '25'],
                ['machine_id' => 22, 'operation_id' => '26'],
                ['machine_id' => 22, 'operation_id' => '27'],
                ['machine_id' => 22, 'operation_id' => '28'],

                ['machine_id' => 23, 'operation_id' => '21'],
                ['machine_id' => 23, 'operation_id' => '22'],
                ['machine_id' => 23, 'operation_id' => '23'],
                ['machine_id' => 23, 'operation_id' => '24'],
                ['machine_id' => 23, 'operation_id' => '25'],
                ['machine_id' => 23, 'operation_id' => '26'],
                ['machine_id' => 23, 'operation_id' => '27'],
                ['machine_id' => 23, 'operation_id' => '28'],

                ['machine_id' => 24, 'operation_id' => '21'],
                ['machine_id' => 24, 'operation_id' => '22'],
                ['machine_id' => 24, 'operation_id' => '23'],
                ['machine_id' => 24, 'operation_id' => '24'],
                ['machine_id' => 24, 'operation_id' => '25'],
                ['machine_id' => 24, 'operation_id' => '26'],
                ['machine_id' => 24, 'operation_id' => '27'],
                ['machine_id' => 24, 'operation_id' => '28'],

                ['machine_id' => 25, 'operation_id' => '21'],
                ['machine_id' => 25, 'operation_id' => '22'],
                ['machine_id' => 25, 'operation_id' => '23'],
                ['machine_id' => 25, 'operation_id' => '24'],
                ['machine_id' => 25, 'operation_id' => '25'],
                ['machine_id' => 25, 'operation_id' => '26'],
                ['machine_id' => 25, 'operation_id' => '27'],
                ['machine_id' => 25, 'operation_id' => '28'],

                ['machine_id' => 26, 'operation_id' => '37'],
                ['machine_id' => 26, 'operation_id' => '38'],
                ['machine_id' => 26, 'operation_id' => '39'],
                ['machine_id' => 26, 'operation_id' => '40'],

                ['machine_id' => 27, 'operation_id' => '21'],
                ['machine_id' => 27, 'operation_id' => '22'],
                ['machine_id' => 27, 'operation_id' => '23'],
                ['machine_id' => 27, 'operation_id' => '24'],
                ['machine_id' => 27, 'operation_id' => '25'],
                ['machine_id' => 27, 'operation_id' => '26'],
                ['machine_id' => 27, 'operation_id' => '27'],
                ['machine_id' => 27, 'operation_id' => '28'],

                ['machine_id' => 28, 'operation_id' => '21'],
                ['machine_id' => 28, 'operation_id' => '22'],
                ['machine_id' => 28, 'operation_id' => '23'],
                ['machine_id' => 28, 'operation_id' => '24'],
                ['machine_id' => 28, 'operation_id' => '25'],
                ['machine_id' => 28, 'operation_id' => '26'],
                ['machine_id' => 28, 'operation_id' => '27'],
                ['machine_id' => 28, 'operation_id' => '28'],

                ['machine_id' => 29, 'operation_id' => '21'],
                ['machine_id' => 29, 'operation_id' => '22'],
                ['machine_id' => 29, 'operation_id' => '23'],
                ['machine_id' => 29, 'operation_id' => '24'],
                ['machine_id' => 29, 'operation_id' => '25'],
                ['machine_id' => 29, 'operation_id' => '26'],
                ['machine_id' => 29, 'operation_id' => '27'],
                ['machine_id' => 29, 'operation_id' => '28'],

                ['machine_id' => 30, 'operation_id' => '2'],
                ['machine_id' => 30, 'operation_id' => '11'],
                ['machine_id' => 30, 'operation_id' => '12'],
                ['machine_id' => 30, 'operation_id' => '13'],
                ['machine_id' => 30, 'operation_id' => '14'],
                ['machine_id' => 30, 'operation_id' => '15'],
                ['machine_id' => 30, 'operation_id' => '16'],
                ['machine_id' => 30, 'operation_id' => '17'],
                ['machine_id' => 30, 'operation_id' => '18'],
                ['machine_id' => 30, 'operation_id' => '3'],
                ['machine_id' => 30, 'operation_id' => '4'],
                ['machine_id' => 30, 'operation_id' => '5'],
                ['machine_id' => 30, 'operation_id' => '6'],
                ['machine_id' => 30, 'operation_id' => '7'],
                ['machine_id' => 30, 'operation_id' => '8'],
                ['machine_id' => 30, 'operation_id' => '9'],
                ['machine_id' => 30, 'operation_id' => '10'],

                ['machine_id' => 31, 'operation_id' => '2'],
                ['machine_id' => 31, 'operation_id' => '11'],
                ['machine_id' => 31, 'operation_id' => '12'],
                ['machine_id' => 31, 'operation_id' => '13'],
                ['machine_id' => 31, 'operation_id' => '14'],
                ['machine_id' => 31, 'operation_id' => '15'],
                ['machine_id' => 31, 'operation_id' => '16'],
                ['machine_id' => 31, 'operation_id' => '17'],
                ['machine_id' => 31, 'operation_id' => '18'],
                ['machine_id' => 31, 'operation_id' => '3'],
                ['machine_id' => 31, 'operation_id' => '4'],
                ['machine_id' => 31, 'operation_id' => '5'],
                ['machine_id' => 31, 'operation_id' => '6'],
                ['machine_id' => 31, 'operation_id' => '7'],
                ['machine_id' => 31, 'operation_id' => '8'],
                ['machine_id' => 31, 'operation_id' => '9'],
                ['machine_id' => 31, 'operation_id' => '10'],

                ['machine_id' => 32, 'operation_id' => '41'],

                ['machine_id' => 33, 'operation_id' => '41'],

                ['machine_id' => 34, 'operation_id' => '41'],
                ['machine_id' => 34, 'operation_id' => '42'],
                ['machine_id' => 34, 'operation_id' => '43'],

                ['machine_id' => 35, 'operation_id' => '19'],
                ['machine_id' => 36, 'operation_id' => '19'],

                ['machine_id' => 37, 'operation_id' => '1'],

                ['machine_id' => 38, 'operation_id' => '44'],

                ['machine_id' => 39, 'operation_id' => '45'],
                ['machine_id' => 40, 'operation_id' => '45'],
                ['machine_id' => 41, 'operation_id' => '45'],
                ['machine_id' => 42, 'operation_id' => '45'],
                ['machine_id' => 43, 'operation_id' => '45'],
                ['machine_id' => 44, 'operation_id' => '45'],

                ['machine_id' => 45, 'operation_id' => '47'],
                ['machine_id' => 45, 'operation_id' => '48'],
                ['machine_id' => 45, 'operation_id' => '49'],
                ['machine_id' => 45, 'operation_id' => '50'],
                ['machine_id' => 45, 'operation_id' => '51'],
                ['machine_id' => 45, 'operation_id' => '52'],
                ['machine_id' => 45, 'operation_id' => '46'],

                ['machine_id' => 46, 'operation_id' => '47'],
                ['machine_id' => 46, 'operation_id' => '48'],
                ['machine_id' => 46, 'operation_id' => '49'],
                ['machine_id' => 46, 'operation_id' => '50'],
                ['machine_id' => 46, 'operation_id' => '51'],
                ['machine_id' => 46, 'operation_id' => '52'],

                ['machine_id' => 47, 'operation_id' => '47'],
                ['machine_id' => 47, 'operation_id' => '48'],
                ['machine_id' => 47, 'operation_id' => '49'],
                ['machine_id' => 47, 'operation_id' => '50'],
                ['machine_id' => 47, 'operation_id' => '51'],
                ['machine_id' => 47, 'operation_id' => '52'],

                ['machine_id' => 48, 'operation_id' => '47'],
                ['machine_id' => 48, 'operation_id' => '48'],
                ['machine_id' => 48, 'operation_id' => '49'],
                ['machine_id' => 48, 'operation_id' => '50'],
                ['machine_id' => 48, 'operation_id' => '51'],
                ['machine_id' => 48, 'operation_id' => '52'],

                ['machine_id' => 49, 'operation_id' => '47'],
                ['machine_id' => 49, 'operation_id' => '48'],
                ['machine_id' => 49, 'operation_id' => '49'],
                ['machine_id' => 49, 'operation_id' => '50'],
                ['machine_id' => 49, 'operation_id' => '51'],
                ['machine_id' => 49, 'operation_id' => '52'],

                ['machine_id' => 50, 'operation_id' => '53'],
                ['machine_id' => 50, 'operation_id' => '54'],
                ['machine_id' => 50, 'operation_id' => '55'],
                ['machine_id' => 50, 'operation_id' => '56'],
                ['machine_id' => 50, 'operation_id' => '57'],

                ['machine_id' => 51, 'operation_id' => '53'],
                ['machine_id' => 51, 'operation_id' => '54'],
                ['machine_id' => 51, 'operation_id' => '55'],
                ['machine_id' => 51, 'operation_id' => '56'],
                ['machine_id' => 51, 'operation_id' => '57'],

                ['machine_id' => 52, 'operation_id' => '53'],
                ['machine_id' => 52, 'operation_id' => '54'],
                ['machine_id' => 52, 'operation_id' => '55'],
                ['machine_id' => 52, 'operation_id' => '56'],
                ['machine_id' => 52, 'operation_id' => '57'],

                ['machine_id' => 53, 'operation_id' => '58'],
                ['machine_id' => 54, 'operation_id' => '58'],
                ['machine_id' => 55, 'operation_id' => '58'],
                ['machine_id' => 56, 'operation_id' => '58'],

                ['machine_id' => 57, 'operation_id' => '59'],

                ['machine_id' => 58, 'operation_id' => '61'],
                ['machine_id' => 58, 'operation_id' => '62'],

                ['machine_id' => 59, 'operation_id' => '61'],
                ['machine_id' => 59, 'operation_id' => '62'],

                ['machine_id' => 60, 'operation_id' => '61'],
                ['machine_id' => 60, 'operation_id' => '62'],

                ['machine_id' => 61, 'operation_id' => '61'],
                ['machine_id' => 61, 'operation_id' => '62'],

                ['machine_id' => 62, 'operation_id' => '61'],
                ['machine_id' => 62, 'operation_id' => '62'],

                ['machine_id' => 63, 'operation_id' => '61'],
                ['machine_id' => 63, 'operation_id' => '62'],

                ['machine_id' => 64, 'operation_id' => '61'],
                ['machine_id' => 64, 'operation_id' => '62'],

                ['machine_id' => 65, 'operation_id' => '61'],
                ['machine_id' => 65, 'operation_id' => '62'],

                ['machine_id' => 66, 'operation_id' => '61'],
                ['machine_id' => 66, 'operation_id' => '62'],

                ['machine_id' => 67, 'operation_id' => '63'],
                ['machine_id' => 67, 'operation_id' => '64'],
                ['machine_id' => 67, 'operation_id' => '65'],
                ['machine_id' => 67, 'operation_id' => '66'],

                ['machine_id' => 68, 'operation_id' => '63'],
                ['machine_id' => 68, 'operation_id' => '64'],
                ['machine_id' => 68, 'operation_id' => '65'],
                ['machine_id' => 68, 'operation_id' => '66'],

                ['machine_id' => 69, 'operation_id' => '63'],
                ['machine_id' => 69, 'operation_id' => '64'],
                ['machine_id' => 69, 'operation_id' => '65'],
                ['machine_id' => 69, 'operation_id' => '66'],

                ['machine_id' => 70, 'operation_id' => '63'],
                ['machine_id' => 70, 'operation_id' => '64'],
                ['machine_id' => 70, 'operation_id' => '65'],
                ['machine_id' => 70, 'operation_id' => '66'],

                ['machine_id' => 71, 'operation_id' => '63'],
                ['machine_id' => 71, 'operation_id' => '64'],
                ['machine_id' => 71, 'operation_id' => '65'],
                ['machine_id' => 71, 'operation_id' => '66'],

                ['machine_id' => 72, 'operation_id' => '63'],
                ['machine_id' => 72, 'operation_id' => '64'],
                ['machine_id' => 72, 'operation_id' => '65'],
                ['machine_id' => 72, 'operation_id' => '66'],

                ['machine_id' => 73, 'operation_id' => '63'],
                ['machine_id' => 73, 'operation_id' => '64'],
                ['machine_id' => 73, 'operation_id' => '77'],
                ['machine_id' => 73, 'operation_id' => '76'],
                ['machine_id' => 73, 'operation_id' => '78'],
                ['machine_id' => 73, 'operation_id' => '79'],

                ['machine_id' => 74, 'operation_id' => '63'],
                ['machine_id' => 74, 'operation_id' => '64'],
                ['machine_id' => 74, 'operation_id' => '77'],
                ['machine_id' => 74, 'operation_id' => '76'],
                ['machine_id' => 74, 'operation_id' => '78'],
                ['machine_id' => 74, 'operation_id' => '79'],

                ['machine_id' => 75, 'operation_id' => '63'],
                ['machine_id' => 75, 'operation_id' => '64'],
                ['machine_id' => 75, 'operation_id' => '77'],
                ['machine_id' => 75, 'operation_id' => '76'],
                ['machine_id' => 75, 'operation_id' => '78'],
                ['machine_id' => 75, 'operation_id' => '79'],

                ['machine_id' => 76, 'operation_id' => '79'],

                ['machine_id' => 77, 'operation_id' => '68'],
                ['machine_id' => 77, 'operation_id' => '69'],
                ['machine_id' => 77, 'operation_id' => '70'],
                ['machine_id' => 77, 'operation_id' => '71'],
                ['machine_id' => 77, 'operation_id' => '72'],
                ['machine_id' => 77, 'operation_id' => '73'],

                ['machine_id' => 78, 'operation_id' => '68'],
                ['machine_id' => 78, 'operation_id' => '69'],
                ['machine_id' => 78, 'operation_id' => '70'],
                ['machine_id' => 78, 'operation_id' => '71'],
                ['machine_id' => 78, 'operation_id' => '72'],
                ['machine_id' => 78, 'operation_id' => '73'],
                ['machine_id' => 78, 'operation_id' => '74'],
                ['machine_id' => 78, 'operation_id' => '75'],

                ['machine_id' => 79, 'operation_id' => '68'],
                ['machine_id' => 79, 'operation_id' => '69'],
                ['machine_id' => 79, 'operation_id' => '70'],
                ['machine_id' => 79, 'operation_id' => '71'],
                ['machine_id' => 79, 'operation_id' => '72'],
                ['machine_id' => 79, 'operation_id' => '73'],
                ['machine_id' => 79, 'operation_id' => '74'],
                ['machine_id' => 79, 'operation_id' => '75'],

                ['machine_id' => 80, 'operation_id' => '68'],
                ['machine_id' => 80, 'operation_id' => '69'],
                ['machine_id' => 80, 'operation_id' => '70'],
                ['machine_id' => 80, 'operation_id' => '71'],
                ['machine_id' => 80, 'operation_id' => '72'],
                ['machine_id' => 80, 'operation_id' => '73'],
                ['machine_id' => 80, 'operation_id' => '74'],
                ['machine_id' => 80, 'operation_id' => '75'],

                ['machine_id' => 81, 'operation_id' => '68'],
                ['machine_id' => 81, 'operation_id' => '69'],
                ['machine_id' => 81, 'operation_id' => '70'],
                ['machine_id' => 81, 'operation_id' => '71'],
                ['machine_id' => 81, 'operation_id' => '72'],
                ['machine_id' => 81, 'operation_id' => '73'],
                ['machine_id' => 81, 'operation_id' => '74'],
                ['machine_id' => 81, 'operation_id' => '75'],

                ['machine_id' => 82, 'operation_id' => '68'],
                ['machine_id' => 82, 'operation_id' => '69'],
                ['machine_id' => 82, 'operation_id' => '70'],
                ['machine_id' => 82, 'operation_id' => '71'],
                ['machine_id' => 82, 'operation_id' => '72'],
                ['machine_id' => 82, 'operation_id' => '73'],
                ['machine_id' => 82, 'operation_id' => '74'],
                ['machine_id' => 82, 'operation_id' => '75'],

                ['machine_id' => 83, 'operation_id' => '68'],
                ['machine_id' => 83, 'operation_id' => '69'],
                ['machine_id' => 83, 'operation_id' => '70'],
                ['machine_id' => 83, 'operation_id' => '71'],
                ['machine_id' => 83, 'operation_id' => '72'],
                ['machine_id' => 83, 'operation_id' => '73'],
                ['machine_id' => 83, 'operation_id' => '74'],
                ['machine_id' => 83, 'operation_id' => '75'],

                ['machine_id' => 84, 'operation_id' => '68'],
                ['machine_id' => 84, 'operation_id' => '69'],
                ['machine_id' => 84, 'operation_id' => '70'],
                ['machine_id' => 84, 'operation_id' => '71'],
                ['machine_id' => 84, 'operation_id' => '72'],
                ['machine_id' => 84, 'operation_id' => '73'],
                ['machine_id' => 84, 'operation_id' => '74'],
                ['machine_id' => 84, 'operation_id' => '75'],

                ['machine_id' => 85, 'operation_id' => '68'],
                ['machine_id' => 85, 'operation_id' => '69'],
                ['machine_id' => 85, 'operation_id' => '70'],
                ['machine_id' => 85, 'operation_id' => '71'],
                ['machine_id' => 85, 'operation_id' => '72'],
                ['machine_id' => 85, 'operation_id' => '73'],
                ['machine_id' => 85, 'operation_id' => '74'],
                ['machine_id' => 85, 'operation_id' => '75'],

                ['machine_id' => 86, 'operation_id' => '68'],
                ['machine_id' => 86, 'operation_id' => '69'],
                ['machine_id' => 86, 'operation_id' => '70'],
                ['machine_id' => 86, 'operation_id' => '71'],
                ['machine_id' => 86, 'operation_id' => '72'],
                ['machine_id' => 86, 'operation_id' => '73'],
                ['machine_id' => 86, 'operation_id' => '74'],
                ['machine_id' => 86, 'operation_id' => '75'],

                ['machine_id' => 87, 'operation_id' => '47'],
                ['machine_id' => 87, 'operation_id' => '48'],
                ['machine_id' => 87, 'operation_id' => '49'],
                ['machine_id' => 87, 'operation_id' => '50'],
                ['machine_id' => 87, 'operation_id' => '51'],
                ['machine_id' => 87, 'operation_id' => '52'],

                ['machine_id' => 88, 'operation_id' => '68'],
                ['machine_id' => 88, 'operation_id' => '69'],
                ['machine_id' => 88, 'operation_id' => '70'],
                ['machine_id' => 88, 'operation_id' => '71'],
                ['machine_id' => 88, 'operation_id' => '72'],
                ['machine_id' => 88, 'operation_id' => '73'],
                ['machine_id' => 88, 'operation_id' => '74'],
                ['machine_id' => 88, 'operation_id' => '75'],

                ['machine_id' => 89, 'operation_id' => '68'],
                ['machine_id' => 89, 'operation_id' => '69'],
                ['machine_id' => 89, 'operation_id' => '70'],
                ['machine_id' => 89, 'operation_id' => '71'],
                ['machine_id' => 89, 'operation_id' => '72'],
                ['machine_id' => 89, 'operation_id' => '73'],
                ['machine_id' => 89, 'operation_id' => '74'],
                ['machine_id' => 89, 'operation_id' => '75'],

                ['machine_id' => 90, 'operation_id' => '68'],
                ['machine_id' => 90, 'operation_id' => '69'],
                ['machine_id' => 90, 'operation_id' => '70'],
                ['machine_id' => 90, 'operation_id' => '71'],
                ['machine_id' => 90, 'operation_id' => '72'],
                ['machine_id' => 90, 'operation_id' => '73'],
                ['machine_id' => 90, 'operation_id' => '74'],
                ['machine_id' => 90, 'operation_id' => '75'],

                ['machine_id' => 91, 'operation_id' => '67'],
                ['machine_id' => 92, 'operation_id' => '67'],
                ['machine_id' => 93, 'operation_id' => '67'],
                ['machine_id' => 94, 'operation_id' => '67'],
                ['machine_id' => 95, 'operation_id' => '67'],

                ['machine_id' => 96, 'operation_id' => '80'],
                ['machine_id' => 97, 'operation_id' => '80'],
                ['machine_id' => 98, 'operation_id' => '80'],
                ['machine_id' => 99, 'operation_id' => '80'],
                ['machine_id' => 100, 'operation_id' => '80'],
                ['machine_id' => 101, 'operation_id' => '80'],
                ['machine_id' => 102, 'operation_id' => '80'],
                ['machine_id' => 103, 'operation_id' => '80'],

                ['machine_id' => 104, 'operation_id' => '80'],
                ['machine_id' => 104, 'operation_id' => '81'],
                ['machine_id' => 104, 'operation_id' => '82'],

                ['machine_id' => 105, 'operation_id' => '80'],
                ['machine_id' => 105, 'operation_id' => '81'],
                ['machine_id' => 105, 'operation_id' => '82'],

                ['machine_id' => 106, 'operation_id' => '80'],
                ['machine_id' => 106, 'operation_id' => '81'],
                ['machine_id' => 106, 'operation_id' => '82'],

                ['machine_id' => 107, 'operation_id' => '80'],
                ['machine_id' => 107, 'operation_id' => '81'],
                ['machine_id' => 107, 'operation_id' => '82'],

                ['machine_id' => 108, 'operation_id' => '83'],
                ['machine_id' => 109, 'operation_id' => '83'],

                ['machine_id' => 110, 'operation_id' => '84'],
                ['machine_id' => 110, 'operation_id' => '85'],
                ['machine_id' => 110, 'operation_id' => '86'],
                ['machine_id' => 110, 'operation_id' => '87'],
                ['machine_id' => 110, 'operation_id' => '88'],
                ['machine_id' => 110, 'operation_id' => '105'],
                ['machine_id' => 110, 'operation_id' => '106'],
                ['machine_id' => 110, 'operation_id' => '110'],
                ['machine_id' => 110, 'operation_id' => '97'],
                ['machine_id' => 110, 'operation_id' => '118'],

                ['machine_id' => 111, 'operation_id' => '84'],
                ['machine_id' => 111, 'operation_id' => '85'],
                ['machine_id' => 111, 'operation_id' => '86'],
                ['machine_id' => 111, 'operation_id' => '87'],
                ['machine_id' => 111, 'operation_id' => '88'],
                ['machine_id' => 111, 'operation_id' => '105'],
                ['machine_id' => 111, 'operation_id' => '106'],
                ['machine_id' => 111, 'operation_id' => '110'],
                ['machine_id' => 111, 'operation_id' => '97'],
                ['machine_id' => 111, 'operation_id' => '118'],

                ['machine_id' => 112, 'operation_id' => '84'],
                ['machine_id' => 112, 'operation_id' => '85'],
                ['machine_id' => 112, 'operation_id' => '86'],
                ['machine_id' => 112, 'operation_id' => '87'],
                ['machine_id' => 112, 'operation_id' => '88'],
                ['machine_id' => 112, 'operation_id' => '105'],
                ['machine_id' => 112, 'operation_id' => '106'],
                ['machine_id' => 112, 'operation_id' => '110'],
                ['machine_id' => 112, 'operation_id' => '97'],
                ['machine_id' => 112, 'operation_id' => '118'],

                ['machine_id' => 113, 'operation_id' => '84'],
                ['machine_id' => 113, 'operation_id' => '85'],
                ['machine_id' => 113, 'operation_id' => '86'],
                ['machine_id' => 113, 'operation_id' => '87'],
                ['machine_id' => 113, 'operation_id' => '88'],
                ['machine_id' => 113, 'operation_id' => '105'],
                ['machine_id' => 113, 'operation_id' => '106'],
                ['machine_id' => 113, 'operation_id' => '110'],
                ['machine_id' => 113, 'operation_id' => '97'],
                ['machine_id' => 113, 'operation_id' => '118'],

                ['machine_id' => 114, 'operation_id' => '89'],
                ['machine_id' => 115, 'operation_id' => '90'],
                ['machine_id' => 116, 'operation_id' => '90'],
                ['machine_id' => 117, 'operation_id' => '90'],
                ['machine_id' => 118, 'operation_id' => '91'],
                ['machine_id' => 119, 'operation_id' => '92'],

                ['machine_id' => 120, 'operation_id' => '94'],
                ['machine_id' => 120, 'operation_id' => '116'],
                ['machine_id' => 120, 'operation_id' => '108'],

                ['machine_id' => 121, 'operation_id' => '94'],
                ['machine_id' => 121, 'operation_id' => '116'],
                ['machine_id' => 121, 'operation_id' => '108'],

                ['machine_id' => 122, 'operation_id' => '94'],
                ['machine_id' => 122, 'operation_id' => '116'],
                ['machine_id' => 122, 'operation_id' => '108'],

                ['machine_id' => 123, 'operation_id' => '93'],
                ['machine_id' => 123, 'operation_id' => '108'],

                ['machine_id' => 124, 'operation_id' => '93'],
                ['machine_id' => 124, 'operation_id' => '108'],

                ['machine_id' => 125, 'operation_id' => '93'],
                ['machine_id' => 125, 'operation_id' => '108'],

                ['machine_id' => 126, 'operation_id' => '95'],
                ['machine_id' => 126, 'operation_id' => '107'],

                ['machine_id' => 127, 'operation_id' => '95'],
                ['machine_id' => 127, 'operation_id' => '107'],

                ['machine_id' => 128, 'operation_id' => '95'],
                ['machine_id' => 128, 'operation_id' => '107'],

                ['machine_id' => 129, 'operation_id' => '95'],
                ['machine_id' => 129, 'operation_id' => '107'],

                ['machine_id' => 130, 'operation_id' => '96'],
                ['machine_id' => 131, 'operation_id' => '96'],
                ['machine_id' => 132, 'operation_id' => '96'],
                ['machine_id' => 133, 'operation_id' => '96'],

                ['machine_id' => 134, 'operation_id' => '115'],
                ['machine_id' => 134, 'operation_id' => '111'],
                ['machine_id' => 134, 'operation_id' => '113'],

                ['machine_id' => 135, 'operation_id' => '115'],
                ['machine_id' => 135, 'operation_id' => '111'],
                ['machine_id' => 135, 'operation_id' => '113'],

                ['machine_id' => 136, 'operation_id' => '115'],
                ['machine_id' => 136, 'operation_id' => '111'],
                ['machine_id' => 136, 'operation_id' => '113'],

                ['machine_id' => 137, 'operation_id' => '101'],
                ['machine_id' => 137, 'operation_id' => '102'],
                ['machine_id' => 137, 'operation_id' => '103'],
                ['machine_id' => 137, 'operation_id' => '104'],

                ['machine_id' => 138, 'operation_id' => '101'],
                ['machine_id' => 138, 'operation_id' => '102'],
                ['machine_id' => 138, 'operation_id' => '103'],
                ['machine_id' => 138, 'operation_id' => '104'],

                ['machine_id' => 139, 'operation_id' => '101'],
                ['machine_id' => 139, 'operation_id' => '102'],
                ['machine_id' => 139, 'operation_id' => '103'],
                ['machine_id' => 139, 'operation_id' => '104'],

                ['machine_id' => 140, 'operation_id' => '101'],
                ['machine_id' => 140, 'operation_id' => '102'],
                ['machine_id' => 140, 'operation_id' => '103'],
                ['machine_id' => 140, 'operation_id' => '104'],

                ['machine_id' => 141, 'operation_id' => '100'],
                ['machine_id' => 141, 'operation_id' => '114'],

                ['machine_id' => 142, 'operation_id' => '100'],
                ['machine_id' => 142, 'operation_id' => '114'],

                ['machine_id' => 143, 'operation_id' => '100'],
                ['machine_id' => 143, 'operation_id' => '114'],

                ['machine_id' => 144, 'operation_id' => '100'],
                ['machine_id' => 144, 'operation_id' => '114'],

                ['machine_id' => 145, 'operation_id' => '100'],
                ['machine_id' => 145, 'operation_id' => '114'],

                ['machine_id' => 146, 'operation_id' => '98'],
                ['machine_id' => 147, 'operation_id' => '79'],
                ['machine_id' => 148, 'operation_id' => '98'],

                ['machine_id' => 149, 'operation_id' => '118'],
                ['machine_id' => 149, 'operation_id' => '97'],
                ['machine_id' => 149, 'operation_id' => '117'],

                ['machine_id' => 150, 'operation_id' => '112'],
                ['machine_id' => 151, 'operation_id' => '112'],
                 

            ],
        );
    }
}
